# Dependencies
highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-email-protect

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - .gitignore
  - .ruby-version
  - Makefile
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - scripts/
  - .github/
  - .nova/

include:
  - .htaccess
  # bootstrap js
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map
  # bootstrap icons
  - node_modules/bootstrap-icons/font/bootstrap-icons.min.css
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff
  - node_modules/bootstrap-icons/font/fonts/bootstrap-icons.woff2

keep_files:
  - .well-known

# Site
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--excerpt-->

# jekyll-sass-converter
# https://github.com/jekyll/jekyll-sass-converter?tab=readme-ov-file#configuration-options
sass:
  style: compressed
  quiet_deps: true
  # Silence various deprecation warnings from Bootstrap.
  # This is a known issue and will likely be resolved in v6.
  #
  # See the following issues:
  #   - https://github.com/twbs/bootstrap/issues/41915
  #   - https://github.com/twbs/bootstrap/issues/40962
  #   - https://github.com/twbs/bootstrap/issues/40849
  #
  # Sass Docs:
  #   https://sass-lang.com/documentation/breaking-changes/import/
  silence_deprecations: ['import', 'if-function', 'global-builtin', 'color-functions']

# Metadata
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: 'https://www.jessesquires.com'
logo: logo.png
favicon: /favicon.ico
timezone: America/Los_Angeles

# Author
author:
  name: 'Jesse Squires'
  email: jesse@jessesquires.com
  twitter: jesse_squires
  avatar: me.jpg

# Archives Config
jekyll-archives:
  enabled:
    - year
  layout: archive
  permalinks:
    year: '/blog/archive/:year/'

# Data
feeds:
  limit: 30
  rss: '/feed.xml'
  json: '/feed.json'
  rss-updates-only: '/feeds/updates.xml'
  json-updates-only: '/feeds/updates.json'

# URLs
img_url: '/img/'
blog_url: '/blog/'
categories_url: '/blog/categories/'
tags_url: '/blog/tags/'
archive_url: '/blog/archive/'
stats_url: 'https://stats.jessesquires.com'
